name: MSBuild

on:
  push:
    branches: [ main, stable/* ]
  pull_request:
    branches: [ main, stable/* ]

env:
  SOLUTION_FILE_PATH: build/src/AnkhSVN.sln

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
      with:
        path: build

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1

    - name: Setup version
      working-directory: build
      run: cmd.exe /C scripts\gh-version-setup ${{ github.run_number }}

    - name: Build 2017-2019
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /v:m /restore /p:UseVsSdkVersion=15.0 /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}} @build\scripts\msbuild-version.rsp

    - name: Package vsix 2017-2019
      uses: actions/upload-artifact@v2
      with:
        name: Ankh-VSIX-2017-2019
        path: build/src/Ankh.Package/bin/release/Ankh.Package.vsix

    - name: Build 2019
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /v:m /restore /t:rebuild /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}} @build\scripts\msbuild-version.rsp

    - name: Package vsix 2019
      uses: actions/upload-artifact@v2
      with:
        name: Ankh-VSIX-2019-only
        path: build/src/Ankh.Package/bin/release/Ankh.Package.vsix

    - name: Build 2022
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /v:m /restore /t:rebuild /p:UseVsSdkVersion=17.0 /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}} @build\scripts\msbuild-version.rsp

    - name: Package vsix 2022
      uses: actions/upload-artifact@v2
      with:
        name: Ankh-VSIX-2022
        path: build/src/Ankh.Package/bin/release/Ankh.Package.vsix

#    - name: Build 2012-2015
#      working-directory: ${{env.GITHUB_WORKSPACE}}
#      run: msbuild /m /v:m /restore /t:rebuild /p:UseVsSdkVersion=11.0 /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}} @build\scripts\msbuild-version.rsp
#
#    - name: Package vsix 2012-2015
#      uses: actions/upload-artifact@v2
#      with:
#        name: Ankh-VSIX-2012-2015
#        path: build/src/Ankh.Package/bin/release/Ankh.Package.vsix
